name: CI
on:
  workflow_dispatch:
  pull_request:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791 # v2.5.0
    - name: Test Script
      run: |
        ./test_script.sh
